[matching]
priority_keywords = [
    "同人志",
]
# 是否允许移动到无编号的二级文件夹
allow_move_to_unnumbered = false

[blacklist]
folders = [
    "[ALICESOFT]",
    "[こわれもの (抹茶さま、mattya604)]",
    "[ザンクロー]",
    "[JTveemo]",
]

[folder_templates]
templates = [
    "1. 同人志",
    "2. 商业志",
]
