[matching]
priority_keywords = [
    "同人志",
]
allow_move_to_unnumbered = false

[blacklist]
folders = [
    "[JTveemo]",
    "[こわれもの (抹茶さま、mattya604)]",
    "[ALICESOFT]",
    "[影おじ (隠れエリア)]",
    "[ザンクロー]",
]

[folder_templates]
templates = [
    "1. 同人志",
    "2. 商业志",
]

[folder_moving]
enabled = true
blacklist = [
    "视频",
    "动图",
]
